export const children = [
  {
    slug: "yubraj-mijar",
    name: "Yubraj Mijar",
    age: 8,
    dob: "March 4, 2016",
    birthPlace: "Triveni, Bajura",
    fatherName: "Deceased",
    motherName: "Remarried, unable to care for him",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Yubraj Mijar was recently welcomed into our childcare home. His father passed away when Yubraj was just two years old, and due to poverty his mother later remarried and was unable to keep him with her.",
      "His grandmother stepped in to raise him, but he was suffering from malnutrition. Seeing his critical condition, the Triveni municipality office referred his case to Concern Bajura.",
      "Nowadays Yubraj is studying in class 1 at Basanta Bal Maitri Primary School, and is slowly regaining his strength with regular meals and care.",
    ],
  },
  {
    slug: "sita-thapa",
    name: "Sita Thapa",
    age: 10,
    dob: "June 12, 2014",
    birthPlace: "Budhiganga, Bajura",
    fatherName: "Hari Thapa",
    motherName: "Maya Thapa",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Sita Thapa lives in the remote village of Budhiganga, nestled within the rugged hills of Bajura. Like many children in her community, access to quality education is a daily challenge, often hindered by difficult terrain and economic hardship. Despite these obstacles, Sita's determination is unwavering.",
      "Every morning, she walks over an hour to reach the local primary school. Her teachers describe her as exceptionally curious and a natural leader among her peers. She loves studying science and hopes to one day return to her village as a teacher, empowering the next generation.",
      "Through the support of Concern Bajura, Sita now receives essential school supplies, uniform assistance, and access to supplementary learning materials. This intervention not only keeps her in the classroom but also lifts the financial burden from her parents, who work tirelessly as subsistence farmers.",
    ],
  },
  {
    slug: "ramesh-bk",
    name: "Ramesh BK",
    age: 7,
    dob: "October 21, 2017",
    birthPlace: "Swami Kartik, Bajura",
    fatherName: "Krishna BK",
    motherName: "Sarita BK",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Ramesh BK is one of the youngest children in our program, full of energy and always the first to smile when new visitors arrive. His family works as day laborers in Bajura district, and school fees were once out of reach.",
      "With support from Concern Bajura, Ramesh is now enrolled in the local primary school and receives regular health check-ups. His teachers say he has taken a strong liking to drawing and storytelling.",
      "Concern Bajura continues to support his family with school supplies and nutrition guidance so Ramesh can keep growing and learning.",
    ],
  },
  {
    slug: "anjali-gurung",
    name: "Anjali Gurung",
    age: 14,
    dob: "January 9, 2010",
    birthPlace: "Budhinanda, Bajura",
    fatherName: "Tek Bahadur Gurung",
    motherName: "Kamala Gurung",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Anjali Gurung is one of the oldest students supported through Concern Bajura's education program, currently studying at a secondary school in Bajura district.",
      "She walks nearly two hours each day to reach her school, carrying her books wrapped carefully to protect them from the weather. Anjali dreams of becoming a nurse so she can care for people in her own community.",
      "With the help of school supplies, a uniform, and mentorship from Concern Bajura, Anjali continues to excel in her studies and encourages younger children in her village to stay in school.",
    ],
  },
  {
    slug: "bishal-khatri",
    name: "Bishal Khatri",
    age: 9,
    dob: "August 2, 2015",
    birthPlace: "Jagannath, Bajura",
    fatherName: "Deceased",
    motherName: "Radha Khatri",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Bishal Khatri lost his father at a young age, leaving his mother to raise him and his siblings alone in a village with very limited work opportunities.",
      "Since joining Concern Bajura's program, Bishal has received consistent meals, school materials, and a safe space to study after school hours. He's known among staff for his curiosity about how things work.",
      "Concern Bajura continues to support his mother with resources so the family can stay together while Bishal focuses on his education.",
    ],
  },
  {
    slug: "maya-shrestha",
    name: "Maya Shrestha",
    age: 11,
    dob: "May 27, 2013",
    birthPlace: "Budhiganga, Bajura",
    fatherName: "Bhim Shrestha",
    motherName: "Deceased",
    image: "https://placehold.co/500x600/a8a29e/a8a29e?text=+",
    story: [
      "Maya Shrestha lost her mother when she was six years old. Since then, her father has worked hard to support her and her younger brother, but resources have always been stretched thin.",
      "Maya is in class 5 and loves participating in her school's cultural programs. Her teachers describe her as thoughtful and hardworking, often helping her classmates with their studies.",
      "Through Concern Bajura's support, Maya receives school supplies and nutritional support, helping ease the load on her father while she continues her education.",
    ],
  },
];

export function getChildBySlug(slug) {
  return children.find((child) => child.slug === slug);
}
